import { type ArgumentsHost, Catch, type ExceptionFilter, HttpException, HttpStatus } from "@nestjs/common";

@Catch()
export class ValidationExceptionFilter implements ExceptionFilter {
  catch(exception: any, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse();
    const request = ctx.getRequest();

    // Verifica se o erro √© de valida√ß√£o do Mongoose
    if (exception.name === 'ValidationError') {
      console.log('üöÄ ~ file: validation-exception-filter.ts:12 ~ ValidationExceptionFilter ~ exception üöÄ ‚û°‚û°', exception);
      const errors = Object.keys(exception.errors).map((key) => ({
        field: key,
        message: exception.errors[key].message,
      }));

      // Responde com um erro HTTP 400 (Bad Request) e informa√ß√µes detalhadas
      return response.status(HttpStatus.BAD_REQUEST).json({
        statusCode: HttpStatus.BAD_REQUEST,
        timestamp: new Date().toISOString(),
        path: request.url,
        message: 'Validation failed',
        errors,
      });
    }

    // Para outros erros, repassa normalmente
    if (exception instanceof HttpException) {
      const status = exception.getStatus();
      const exceptionResponse = exception.getResponse();
      return response.status(status).json({
        ...(
          typeof exceptionResponse === 'object' ? exceptionResponse : { message: exceptionResponse }
        ),
        statusCode: status,
        timestamp: new Date().toISOString(),
        path: request.url,
      });
    }
    // Caso n√£o seja uma exce√ß√£o esperada, retorna um erro gen√©rico
    return response.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
      statusCode: HttpStatus.INTERNAL_SERVER_ERROR,
      timestamp: new Date().toISOString(),
      path: request.url,
      message: exception.message ?? 'Internal server error',
    });
  }
}